Lefromage
specht/schul-dashboard pull request #20
Opened 2023-04-24 14:50 UTC by gpeter2706

- Technikämter der Klassen können Probleme mitt der Technik an "user_who_can_manage_tablets" melden
- "user_who_can_manage_tablets" kann die Meldungen einsehen
- Neue Rolle "techpost"

2023-04-24 15:05 UTC, specht commented on src/ruby/credentials.template.rb
> +TECHPOST_USERS = []
Bitte in CAN_REPORT_TECH_PROBLEM umbennen

2023-04-24 15:25 UTC, specht requested changes
`code` bitte raus, dafür über `token` eindeutig referenzieren, keine Datei abspeichern, alle Infos in der Datenbank

2023-04-24 15:25 UTC, specht commented on src/static/techpost.html
> +#{require_user!}
require_techpost_user!

2023-04-24 15:25 UTC, specht commented on src/static/techpost.html
> +    moment.locale('de');
Fix indentation

2023-04-25 19:32 UTC, gpeter2706 reviewed
lefromage

2023-05-08 18:06 UTC, closed without merging